name: Build Android APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Release APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Regenerate Android files
        run: |
          if [ ! -f android/app/src/main/AndroidManifest.xml ]; then
            flutter create . --platforms android
          else
            cp android/app/src/main/AndroidManifest.xml AndroidManifest.xml.bak
            flutter create . --platforms android
            cp AndroidManifest.xml.bak android/app/src/main/AndroidManifest.xml
          fi

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Get dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release --verbose
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g"
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aura-music-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
